check go generation has been rerun

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -108,12 +108,13 @@ jobs:
 
   # changes allows us to only run a job on changed packages
   changes:
-    name: Go Changes
+    name: Change Detection
     runs-on: ubuntu-latest
     outputs:
       # Expose matched filters as job 'packages' output variable
-      packages: ${{ steps.filter.outputs.changes }}
+      packages: ${{ steps.filter_go.outputs.changes }}
       package_count: ${{ steps.length.outputs.FILTER_LENGTH }}
+      solidity_changes: ${{ steps.filter_solidity.outputs.any_changed }}
     steps:
       - uses: actions/checkout@v2
         with:
@@ -122,18 +123,24 @@ jobs:
 
       # For pull requests it's not necessary to checkout the code
       - uses: dorny/paths-filter@v2
-        id: filter
+        id: filter_go
         with:
           filters: |
             core: 'core/**'
             tools: 'tools/**'
             ethergo: 'ethergo/**'
+      - name: Get specific changed files
+        id: filter_solidity
+        uses: tj-actions/changed-files@v26.1
+        with:
+          files: |
+            *.sol
       - id: length
         run: |
           export FILTER_LENGTH=$(echo $FILTERED_PATHS | jq '. | length')
           echo "##[set-output name=FILTER_LENGTH;]$(echo $FILTER_LENGTH)"
         env:
-          FILTERED_PATHS: ${{ steps.filter.outputs.changes }}
+          FILTERED_PATHS: ${{ steps.filter_go.outputs.changes }}
 
   # make sure the build works
   build:
@@ -223,3 +230,58 @@ jobs:
           # see: https://github.com/golangci/golangci-lint/issues/337#issuecomment-510136513
           GOGC: 20
           GOPRIVATE: "GOPRIVATE=github.com/synapsecns/synapse-node"
+
+  # check if we need to rerun go generate as a result of solidity changes. Note, this will only run on solidity changes
+  check-generation:
+    name: Go Generate
+    runs-on: ubuntu-latest
+    needs: changes
+    if: ${{ github.event_name != 'pull_request' && needs.changes.outputs.solidity_changes }}
+    strategy:
+      matrix:
+        # only do on core for now
+        package: ['core']
+    steps:
+      - uses: actions/setup-go@v3
+        with:
+          go-version: 1.18
+
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+          submodules: 'recursive'
+
+      - name: authenticate with github for private go modules
+        uses: fusion-engineering/setup-git-credentials@v2
+        with:
+          credentials: https://0xnero:${{secrets.GIT_TOKEN }}@github.com/
+
+
+      - name: Go modules cache
+        uses: actions/cache@v2
+        with:
+          # see https://github.com/mvdan/github-actions-golang
+          path: |
+            ~/go/pkg/mod
+            ~/.cache/go-build
+            ~/Library/Caches/go-build
+            %LocalAppData%\go-build
+          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+          restore-keys: |
+            ${{ runner.os }}-go-
+
+      - name: Try Go Generate
+        run: |
+          go generate ./...
+
+      - name: Verify Changed files
+        uses: tj-actions/verify-changed-files@v10.1
+        id: verify-changed-files
+        with:
+          files: |
+            *.go
+
+        # Fail if files need regeneration
+      - name: Run if files need to be regenerated
+        if: steps.verify-changed-files.outputs.files_changed == 'true'
+        run: exit 1
