Sinner  (#1380)
* init

* stashing at prev checkpoint to resolve build issues

* updating graphql

* live filling updates

* stash prev changes before tests

* update queries w/tests

* update api and cli

* stash before deploy

* api tests

* lint

* lint

* lint + gen

* code cov

* gen

* adding code cov

* lint + test + coderabbit suggestions

* symlink

* edits

* hold

* Update go.mod

* sinner docker + main.go

* sinner test flake, bytes -> hex string update, update assert use, lint

* update logging

* deprecate port flag

* updating fetch ceil

* adding concurrency during parse store

* add comments

* gen (stringer)

* add build to .goreleaser.yml

* build

* Revert "build" [goreleaser]

This reverts commit 8c61076f3652d7c8a9056c749c725bae2323f6f3.

* fix goreleaser [goreleaser]

* fix replacement issue

* [sinner] add start readme (#1499)

* add start readme

* fix https://github.com/synapsecns/sanguine/pull/1380/files#r1371810612

---------

Co-authored-by: Trajan0x <trajan0x@users.noreply.github.com>

* sinner strings for contract_type (#1498)

Co-authored-by: Trajan0x <trajan0x@users.noreply.github.com>

* trajan edits

* nits

* explorer update

* Sinner: resolvers and updating db read functions (#1514)

* init staging

* add more db read functions

* update model to where

* update filters

* hash

* Revert "hash"

This reverts commit 9b159df240c39f588420dc059520fad6e83e97f4.

* remove unused db mocks

* handle invalid port

---------

Co-authored-by: Trajan0x <trajan0x@users.noreply.github.com>

* type fix

* simplify w generics

* add go error group to unified command + updated read.go

* code rabbit nit

* logger fix

* Parser, API, and config updates

* tests, sinner/indexer updates, db updates

* lint + refactor graphql + db

* Add log range asc to API

* [goreleaser]

* Update README.md

* refactor indexer

* exit 1 on fail

* update scribe fetcher and pagination behavior

* mysql context

* mysql + refresh rate

* update config and readme + [goreleaser]

* update tests

* typo + [goreleaser]

* prom exporter gen

* revert abi - [goreleaser]

* [goreleaser]

* specify varchar length for indexing [goreleaser]

* update 64 to 66 to account for 0x [goreleaser]

* update api

* [goreleaser]

* gen

* update comment

* [goreleaser]

* add asc flag

* [goroutine]

* [goreleaser]

---------

Co-authored-by: Trajan0x <trajan0x@users.noreply.github.com>
Co-authored-by: trajan0x <83933037+trajan0x@users.noreply.github.com>

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -200,6 +200,12 @@ jobs:
               fi
             done
 
+            # Check if max retries is exceeded for this package.
+            if [ $retries -eq $max_num_retries ]; then
+                echo "Max retries exceeded for $pkg"
+                exit 1
+            fi
+
             if [ -f profile.cov ]; then
               tail -n +2 profile.cov >> coverage.txt
               rm profile.cov
