Use `gotestsum` to retry individually failed tests (#1371)
* Feat: use gotestsum to retry individually failed tests

* Cleanup: fraud comments (trigger ci)

* Try running gotestsum directly

* Remove commented workflow

* Redo

* faster install of gotestyourself

* Try package-level retries w/ docker cleanup

* Cleanup: add comments to package level retries

* Remove docker cleanup

* Bump max pkg retries

---------

Co-authored-by: Trajan0x <trajan0x@users.noreply.github.com>

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -137,9 +137,16 @@ jobs:
           done
 
       - name: Install pyroscope-ci
-        uses: jaxxstorm/action-install-gh-release@v1.5.0
+        uses: jaxxstorm/action-install-gh-release@v1.10.0
         with: # Grab the latest version
           repo: pyroscope-io/ci
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Install gotestsum
+        uses: jaxxstorm/action-install-gh-release@v1.10.0
+        with: # Grab the latest version
+          repo: gotestyourself/gotestsum
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
@@ -169,25 +176,34 @@ jobs:
           GOGC: -1
 
       - name: Test
-        uses: nick-fields/retry@v2
-        with:
-          command: |
-            set -e
-            cd ${{ matrix.package }}
-            echo "mode: atomic" > coverage.txt
-            for pkg in $(go list ./...); do
-              #$PYROSCOPE_PATH exec --apiKey=${{ secrets.PYROSCOPE_CLOUD_TOKEN }} -- go test -coverpkg="$pkg" -coverprofile=profile.cov $pkg
-              go test -coverpkg="$pkg" -coverprofile=profile.cov $pkg
-              if [ -f profile.cov ]; then
-                tail -n +2 profile.cov >> coverage.txt
-                rm profile.cov
+        run: |
+          set -e
+          max_num_retries=5
+          cd ${{ matrix.package }}
+          echo "mode: atomic" > coverage.txt
+
+          # Loop through each package and run tests, with package level retries
+          # as well as individual test retries.
+          for pkg in $(go list ./...); do
+            retries=0
+
+            while [ $retries -lt $max_num_retries ]; do
+              if $PYROSCOPE_PATH exec --apiKey=${{ secrets.PYROSCOPE_CLOUD_TOKEN }} -- gotestsum --rerun-fails=5 --packages="$pkg" --format standard-verbose -- -v -coverpkg="$pkg" -coverprofile=profile.cov $pkg; then
+                break
+              else
+                retries=$((retries+1))
+                echo "Retry #$retries: 'gotestsum' command failed for $pkg"
               fi
             done
-            cp coverage.txt profile.cov
-            docker ps
-          on_retry_command: docker rm -f $(docker ps -a -q)
-          max_attempts: 5
-          timeout_minutes: 60
+
+            if [ -f profile.cov ]; then
+              tail -n +2 profile.cov >> coverage.txt
+              rm profile.cov
+            fi
+          done
+
+          cp coverage.txt profile.cov
+          docker ps
         env:
           PYROSCOPE_PATH: '${{ steps.pyroscope-path.outputs.PYROSCOPE_PATH }}'
           ENABLE_MYSQL_TEST: true
