start upterm

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -167,26 +167,30 @@ jobs:
           # no other containers are running at this point so we can use all available memory for compilation
           GOMEMLIMIT: 5GiB
           GOGC: -1
-
-      - name: Test
-        uses: nick-fields/retry@v2
+      - name: Setup upterm session
+        uses: lhotari/action-upterm@v1
         with:
-          command: |
-            set -e
-            cd ${{ matrix.package }}
-            echo "mode: atomic" > coverage.txt
-            for pkg in $(go list ./...); do
-              #$PYROSCOPE_PATH exec --apiKey=${{ secrets.PYROSCOPE_CLOUD_TOKEN }} -- go test -coverpkg="$pkg" -coverprofile=profile.cov $pkg
-              go test -coverpkg="$pkg" -coverprofile=profile.cov $pkg
-              if [ -f profile.cov ]; then
-                tail -n +2 profile.cov >> coverage.txt
-                rm profile.cov
-              fi
-            done
-            cp coverage.txt profile.cov
-            docker ps
-          max_attempts: 2
-          timeout_minutes: 60
+           ## limits ssh access and adds the ssh public key for the user which triggered the workflow
+           limit-access-to-users: trajan0x,cryptomaxplanck,dwasse
+            #      - name: Test
+            #        uses: nick-fields/retry@v2
+            #        with:
+            #          command: |
+            #            set -e
+            #            cd ${{ matrix.package }}
+            #            echo "mode: atomic" > coverage.txt
+            #            for pkg in $(go list ./...); do
+            #              #$PYROSCOPE_PATH exec --apiKey=${{ secrets.PYROSCOPE_CLOUD_TOKEN }} -- go test -coverpkg="$pkg" -coverprofile=profile.cov $pkg
+            #              go test -coverpkg="$pkg" -coverprofile=profile.cov $pkg
+            #              if [ -f profile.cov ]; then
+            #                tail -n +2 profile.cov >> coverage.txt
+            #                rm profile.cov
+            #              fi
+            #            done
+            #            cp coverage.txt profile.cov
+            #            docker ps
+            #          max_attempts: 2
+            #          timeout_minutes: 60
         env:
           PYROSCOPE_PATH: '${{ steps.pyroscope-path.outputs.PYROSCOPE_PATH }}'
           ENABLE_MYSQL_TEST: true
